"""
All the feedback responses generated by OpenAI.
"""
from pedal.core.feedback_category import FeedbackCategory, FeedbackKind
from pedal.core.report import MAIN_REPORT
from pedal.core.feedback import Feedback
from pedal.gpt.constants import TOOL_NAME


class gpt_prompt_feedback(Feedback):
    """

    Args:
        instructions:
    """

    category = FeedbackCategory.INSTRUCTOR
    kind = FeedbackKind.HINT
    justification = 'AI-Generated Feedback'
    title = 'AI-Generated Feedback'
    priority = Feedback.CATEGORIES.GPT
    tool = TOOL_NAME
    valence = 0
    score = 0

    def __init__(self, instructions, **kwargs):
        super().__init__(message=instructions['feedback'], score=instructions['score'], **kwargs)
