"""
All the feedback responses generated by OpenAI.
"""
from pedal.core.feedback_category import FeedbackCategory, FeedbackKind
from pedal.core.report import MAIN_REPORT
from pedal.core.feedback import Feedback
from pedal.gpt.constants import TOOL_NAME


class gpt_prompt_feedback(Feedback):
    """

    Args:
        instructions:
    """

    category = FeedbackCategory.PATTERNS
    kind = FeedbackKind.HINT
    justification = 'AI-Generated Feedback'
    title = 'AI-Generated Feedback'
    priority = Feedback.CATEGORIES.PATTERNS
    tool = TOOL_NAME
    valence = -1  # todo(gpt): possibly look into asking if the feedback is positive or negative

    def __init__(self, instructions, **kwargs):
        super().__init__(message=instructions['feedback'], score=instructions['score'], **kwargs)
